/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/heIAywT8crX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { Button } from "@/components/ui/button";
import { useState } from "react";

export function JavaScriptCalculator() {
  const [result, setResult] = useState<number | string>(0);
  const [input, setInput] = useState("");
  const handleInput = (value: string) => {
    setInput((prevInput) => prevInput + value);
  };
  const handleClear = () => {
    setInput("");
    setResult(0);
  };
  const handleCalculate = () => {
    try {
      setResult(eval(input));
    } catch (error) {
      setResult("Error");
    }
  };
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-gray-100 dark:bg-gray-800">
      <div className="w-full max-w-md bg-white dark:bg-gray-700 rounded-lg shadow-lg p-6">
        <div className="flex flex-col items-end mb-4">
          <div className="text-3xl font-bold text-gray-800 dark:text-gray-200 mb-2" id="display">{result}</div>
          <div className="text-lg text-gray-600 dark:text-gray-400 overflow-x-auto whitespace-nowrap">{input}</div>
        </div>
        <div className="grid grid-cols-4 gap-4">
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-200"
            onClick={handleClear}
            id="clear"
          >
            C
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200"
            onClick={() => handleInput("(")}
          >
            (
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200"
            onClick={() => handleInput(")")}
          >
            )
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200"
            onClick={() => handleInput("/")}
          >
            /
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200"
            onClick={() => handleInput("7")}
            id="seven"
          >
            7
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200"
            onClick={() => handleInput("8")}
            id="eight"
          >
            8
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200"
            onClick={() => handleInput("9")}
            id="nine"
          >
            9
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200"
            onClick={() => handleInput("*")}
          >
            *
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200"
            onClick={() => handleInput("4")}
            id="four"
          >
            4
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200"
            onClick={() => handleInput("5")}
            id="five"
          >
            5
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200"
            onClick={() => handleInput("6")}
            id="six"
          >
            6
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200"
            onClick={() => handleInput("+")}
          >
            +
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200"
            onClick={() => handleInput("1")}
            id="one"
          >
            1
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200"
            onClick={() => handleInput("2")}
            id="two"
          >
            2
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200"
            onClick={() => handleInput("3")}
            id="three"
          >
            3
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200"
            onClick={() => handleInput("-")}
          >
            -
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200"
            onClick={() => handleInput("0")}
            id="zero"
          >
            0
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200"
            onClick={() => handleInput(".")}
            id="decimal"
          >
            .
          </Button>
          <Button
            variant="ghost"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200"
            onClick={() => handleInput("^")}
          >
            ^
          </Button>
          <Button
            variant="ghost"
            id="equals"
            className="text-2xl font-bold text-gray-800 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200"
            onClick={handleCalculate}
          >
            =
          </Button>
        </div>
      </div>
    </div>
  );
}
